const http=require('http');const fs=require('fs');const path=require('path');const crypto=require('crypto');
const PORT=process.env.PORT||3000, ROOT=__dirname, DB=path.join(ROOT,'data.json');
const ADMIN_USER=process.env.ADMIN_USER||'admin', ADMIN_PASS=process.env.ADMIN_PASS||'ChangeMe123!';
let db={shipments:[{trackingNumber:'SBL100001',status:'In Transit',origin:'Lagos, Nigeria',destination:'London, UK',currentLocation:'Dubai, UAE',estimatedDelivery:'2026-10-02',service:'International Express',customerName:'Demo Customer',customerEmail:'customer@example.com',packageType:'Documents',weight:'1 kg',events:[{date:'2026-09-25T09:00',location:'Lagos, Nigeria',status:'Shipment created',note:'Shipment information received.'},{date:'2026-09-26T10:30',location:'Lagos, Nigeria',status:'Picked up',note:'Package collected from sender.'},{date:'2026-09-27T07:45',location:'Lagos, Nigeria',status:'Departed transit hub',note:'Shipment departed Lagos hub.'},{date:'2026-09-27T12:00',location:'Dubai, UAE',status:'In Transit',note:'Shipment is moving through the international network.'}]}]};
try{if(fs.existsSync(DB))db=JSON.parse(fs.readFileSync(DB,'utf8'));}catch(e){}
function save(){fs.writeFileSync(DB,JSON.stringify(db,null,2))}function json(res,obj,status=200){const s=JSON.stringify(obj);res.writeHead(status,{'Content-Type':'application/json','Content-Length':Buffer.byteLength(s)});res.end(s)}
const sessions=new Map();function cookie(req){const m=(req.headers.cookie||'').match(/sid=([^;]+)/);return m&&m[1]}function authed(req){return sessions.has(cookie(req))}
function body(req){return new Promise((resolve,reject)=>{let d='';req.on('data',c=>d+=c);req.on('end',()=>{try{resolve(d?JSON.parse(d):{})}catch(e){reject(e)}})})}
function safeFile(url){let p=url.split('?')[0];if(p==='/')p='/index.html';if(p==='/admin'||p==='/admin/')p='/admin.html';return path.join(ROOT,p.replace(/^\//,''))}
const server=http.createServer(async(req,res)=>{try{let u=new URL(req.url,'http://localhost');
if(req.method==='GET'&&u.pathname==='/api/track'){const n=u.searchParams.get('number')?.trim().toUpperCase();const x=db.shipments.find(s=>s.trackingNumber.toUpperCase()===n);return x?json(res,x):json(res,{error:'Tracking number not found.'},404)}
if(req.method==='POST'&&u.pathname==='/api/login'){const b=await body(req);if(b.username===ADMIN_USER&&b.password===ADMIN_PASS){const sid=crypto.randomBytes(24).toString('hex');sessions.set(sid,Date.now());res.writeHead(200,{'Set-Cookie':`sid=${sid}; HttpOnly; SameSite=Strict; Path=/; Max-Age=86400`,'Content-Type':'application/json'});return res.end(JSON.stringify({ok:true}))}return json(res,{error:'Invalid login details.'},401)}
if(req.method==='POST'&&u.pathname==='/api/logout'){const sid=cookie(req);sessions.delete(sid);res.writeHead(200,{'Set-Cookie':'sid=; Max-Age=0; Path=/','Content-Type':'application/json'});return res.end('{}')}
if(u.pathname.startsWith('/api/admin')){if(!authed(req))return json(res,{error:'Unauthorized'},401);if(req.method==='GET'&&u.pathname==='/api/admin/shipments')return json(res,db.shipments);
if(req.method==='POST'&&u.pathname==='/api/admin/shipments'){const b=await body(req);if(!b.trackingNumber||!b.origin||!b.destination)return json(res,{error:'Tracking number, origin and destination are required.'},400);if(db.shipments.some(s=>s.trackingNumber.toUpperCase()===b.trackingNumber.toUpperCase()))return json(res,{error:'Tracking number already exists.'},409);const s={...b,trackingNumber:b.trackingNumber.toUpperCase(),events:b.events||[]};db.shipments.push(s);save();return json(res,s,201)}
const m=u.pathname.match(/^\/api\/admin\/shipments\/([^/]+)$/);if(m){const n=decodeURIComponent(m[1]);const i=db.shipments.findIndex(s=>s.trackingNumber===n);if(i<0)return json(res,{error:'Shipment not found.'},404);if(req.method==='PUT'){const b=await body(req);db.shipments[i]={...db.shipments[i],...b,trackingNumber:n};save();return json(res,db.shipments[i])}if(req.method==='DELETE'){db.shipments.splice(i,1);save();return json(res,{ok:true})}}
}
if(req.method==='GET'){if(u.pathname==='/admin'||u.pathname==='/admin/'){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});return fs.createReadStream(path.join(ROOT,'admin.html')).pipe(res)}const f=safeFile(req.url);if(f.startsWith(ROOT)&&fs.existsSync(f)){const ext=path.extname(f);const types={'.html':'text/html; charset=utf-8','.css':'text/css','.js':'application/javascript','.json':'application/json','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml','.txt':'text/plain'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream','Cache-Control':ext==='.html'?'no-store':'public, max-age=3600'});return fs.createReadStream(f).pipe(res)}}res.writeHead(404);res.end('Not found');
}catch(e){json(res,{error:'Server error'},500)}});
server.listen(PORT,()=>console.log(`Sky Blue Logistic running on http://localhost:${PORT}`));
